server:
  port: 8080
mybatis:
  mapper-locations:  classpath*:/mybatis/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    name: mydb
    type:  com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/askforleave?characterEncoding=utf-8&serverTimezone=CTT
    username: root
    password: 2012zhong
    driver-class-name: com.mysql.cj.jdbc.Driver